### ISSUE TITLE
v1-rollup: GetCurrentMinute returns inconsistent data

### ISSUE THREAD

**Issue by PaulBernier** [FactomProject/factom#117]
I am using the code of branch `v1-rollup` commit `5edf7247fc876772bed5c68eb78dd4f8e3292b24` (latest at the time of writing).

The `GetCurrentMinute` method returns the `Minute` of the block currently being built together with a `DirectoryBlockHeight` but that DB height is the one of the last saved block and not the block currently being built, which is misleading. I believe it should also be the height of the block being currently built to be conistent.

**Comment by PaulBernier** [comment]
To motivate that change I am calling on the principle of least astonishment: https://en.wikipedia.org/wiki/Principle_of_least_astonishment
For me I was expecting this API to answer: what are you working on right now. And the answer would be, I am working on block 6 at minute 7.

**Comment by WhoSoup** [comment]
`DirectoryBlockHeight` is used throughout the code to indicate the height of the last finished dblock and I don't think just changing it for this one call is a good idea.

The "heights" API call provides multiple heights for this reason. I would suggest that this call be amended to include `LeaderHeight`, which is the height the leaders are currently working on, in addition to dblock height. That would keep it consistent with the rest of the API.

**Comment by PaulBernier** [comment]
Agree, it's not a good idea to change the semantic of `DirectoryBlockHeight` if it has this meaning everywhere else.

The tern "Current" still remains misleading here for a non-initiated person, as the API does return the current minute, but not the current block. Making the documentation of the function more explicit and highlighting this quirk may be satisfactory enough: https://github.com/FactomProject/factom/blob/v1-rollup/currentminute.go#L44. What do you think?

**Comment by carryforward** [comment]
The problem here arose from the way that we arrived at the API calls originally.  We were trying to abstract away the idea of the process lists, as the API was paying attention to things that were in the database.  

To take an example of bitcoin, the blocks are the important thing that represents the blockchain.  The mempool is interesting, and can help you make decisions on fees, etc, but is more ephemeral.  I know that factom is not bitcoin, and the analogy breaks a little, but when things are in the process list they are not yet in the blockchain.

The idea with the `heights` API originally was that you should know if your local node's saved block matched the finalized block that the Federated servers were building.  That is always going to be less than the one that has acknowledgements being made for it.  This was a way to let systems reading the blockchain know if the local node can be relied on.  The leaderheight looked at the acknowledgements going around the p2p network and from there inferred the latest finished block.  It turned out that was an attack vector, and now the leaderheight only lets you know that you are behind when you have already saved almost all the blocks to the database.  It is kind of disappointing to no longer have the feedback when starting up.  Eventually we need to go down the road of implementing a headers-first style download process, where the dblock headers and the admin blocks are downloaded first to quickly determine who the leaders are and how high the blockchain is.  After that, the rest of the blockchain (or just the relevant parts) can be downloaded.  

Now that we are exposing more of the internal workings of the system, and not just the blockchain itself, the names are a bit confusing, because we are mixing ephemeral things (minutes) with permanent things (saved blocks).

I agree, we need to do a better job of separating out permanent data from the ephemeral data.
