### ISSUE TITLE
BUG: factom.GetTransaction() doesn't return error on incorrect hash!

### ISSUE THREAD

**Issue by ilzheev** [FactomProject/factom#138]
Suddenly, `factom.GetTransaction()` doesn't return error on incorrect hash as input.

Reproduce this request using non-existing tx hash:
```golang
factomTx, err := factom.GetTransaction("0129b5e26e40a11e58bbc91722bc1b021b1c38ca084965ce09b25dd33aa7c891")
log.Info(factomTx)
log.Fatal(err)
```

Result:
```
INFO[0001] &{<nil> <nil> <nil>   -1}                    
FATA[0001] <nil> 
```

@WhoSoup @carryforward

**Comment by WhoSoup** [comment]
This doesn't seem to be a bug per se, just a very unintuitive API call. The returned `err` is set only when the call itself fails (aka unable to contact the api / bad request format), but if the hash is not found, that information is transmitted inside the return:

see https://docs.factomprotocol.org/start/factom-api-docs/factomd-api#transaction
> If the input hash is non-existent, the returned fields will be as follows:
> “includedintransactionblock”:“”
> “includedindirectoryblock”:“”
> “includedindirectoryblockheight”:-1

This behavior works as intended: 

```
$ curl -X POST --data-binary "{\"jsonrpc\": \"2.0\", \"id\": 0, \"method\": \"transaction\", \"params\": {\"hash\": \"1129b5e26e40a11e58bbc91722bc1b021b1c38ca084965ce09b25dd33aa7c891\"}}" -H "content-type:text/plain;" https://api.factomd.net/v2
{"jsonrpc":"2.0","id":0,"result":{"includedintransactionblock":"","includedindirectoryblock":"","includedindirectoryblockheight":-1}}
```

Since a change of this nature would affect existing behavior, this is something that should be revised in the next API version.
