### ISSUE TITLE
encrypt

### ISSUE THREAD

**Issue by erotundo** [FactomProject/factom#26]
Hi.

This it's not a issue, it's only for ask to us about factom and it's possible to use to encrypt and decrypt data using factom? can i use the api for that purpose? or in all cases the data goes to a blockchain?

Regards

ER

**Comment by carryforward** [comment]
Good question.  That is more of an application level feature.  Yes it is certainly possible.

At the factomd and blockchain level, there is no encryption.  There is just arbitrary data.  The blockchain treats encrypted and unencrypted data the same way.  

If we coded up some version, it almost certainly would be wrong for most applications.  The encryption would be best left to the designer of your application, who understands the tradeoffs.

here is an older example of how you could have encrypted data in the blockchain.
https://github.com/FactomProject/FactomDocs/tree/master/examples/tax

Typically, the applications we are imagining are synchronizing different stacks of documents.  When you are talking about encryption, that is typically inferring that the blockchain is the content delivery system, rather than a coordination system.  Getting and storing the data is typically an easier problem that determining which is the correct version of the document.

A typical system we imagine is where the document creator would hash and sign the document.  They would put the signed hash in an Entry in a specific Chain.  This would have some meaning to the people they share the document with.  The people they share it with can be in the present, or in the future.  The documents would be delivered through some other channel (email, existing shared file system, etc).  The accuracy and version management would be handled publicly on the blockchain, but only through signed hashes, so even if the encryption was broken, no personal data would get leaked.

**Comment by erotundo** [comment]
Thanks a lot for your response, i'm think my use of this it's not the correctly. I want to make to you another question but tell me first if i can make it here or open other issues o send to you a mail

Thanks again!

ER

**Comment by carryforward** [comment]
here is fine, so others can find it later too.

**Comment by erotundo** [comment]
Ok, the other question has related to use Factom in Android.

i have a android with a linux distro running inside, this distro has the architecture ARMHF, i try with the example of tax install factom using a force architecture but not run. So the guide to install in Linux (32/64) it's available for use in Debian 8 ARMHF?

Thanks

ER

**Comment by carryforward** [comment]
there has been zero factomd testing on either ARM, or Android.  It might work from source, but it is totally unsupported.

https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md

keep in mind the blockchain is currently about 10 GB.
